In [14]:
from sklearn.tree import DecisionTreeClassifier # Import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier # Import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [15]:
# Load the dataset
data = pd.read_csv("cleaned_data/cleaned_asylum_seekers_added.csv")
data = data[data['HDI'] != '..']
data = data.dropna()
decimals = 2    
data['Unemployment rate'] = data['Unemployment rate'].apply(lambda x: round(x, decimals))
data['origin_to_target_dist'] = data['origin_to_target_dist'].apply(lambda x: round(x, decimals))
data.head()

C:\Users\Darren\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,decisions_recognized,decisions_other,Rejected,Otherwise_closed,Total decisions,Successful,...,Origin_latitude,Origin_longitude,origin_to_target_dist,HDI,Unemployment rate,acceptance_rate,accepted/rejected,Encoded procedure type,Encoded Target Country,Encoded Origin
0,2001,South Africa,Angola,G / AR,0.0,0.0,0.0,1.0,0.0,0.0,...,-14.270972,-170.132217,11214.77,0.61,30.9,0.000000,0,1,135,3
1,2001,South Africa,Angola,G / FI,860.0,0.0,36.0,68.0,964.0,860.0,...,-14.270972,-170.132217,11214.77,0.61,30.9,0.892116,3,6,135,3
2,2001,South Africa,Albania,G / AR,0.0,0.0,0.0,1.0,0.0,0.0,...,41.153332,20.168331,11919.88,0.61,30.9,0.000000,0,1,135,1
3,2001,South Africa,Burundi,G / AR,0.0,0.0,0.0,1.0,0.0,0.0,...,12.238333,-1.561593,8114.66,0.61,30.9,0.000000,0,1,135,25
4,2001,South Africa,Burundi,G / FI,808.0,0.0,234.0,7.0,1049.0,808.0,...,12.238333,-1.561593,8114.66,0.61,30.9,0.770257,3,6,135,25

### Training the AdaBoost Classifier

In [16]:
col_names = ['Unemployment rate','Encoded Target Country', 'Encoded procedure type'] # Declare the columns names

# Features
x = data[col_names]  

# Target Variable
y = data['accepted/rejected']

# Instantiate decision tree
dt = DecisionTreeClassifier(random_state=1)

# Instantiate ada
ada = AdaBoostClassifier(base_estimator = dt, n_estimators=180, random_state=1)

# Split dataset into training set and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1) # 80% training and 20% test

# Fit ada to training set
ada.fit(x_train, y_train)

# Compute the probabilities
y_pred_probability = ada.predict_proba(x_test)[:, 1]

### Evaluate AdaBoost Classifier

In [17]:
# Predict test set labels
y_pred = ada.predict(x_test)

# Compute test set accuracy  
acc = accuracy_score(y_test, y_pred)
print("Test set accuracy: ", (acc))

Test set accuracy:  0.8182653436236678